// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS0yatbK58dhN-VRLMp9BbVEePCVTkiB4',
    appId: '1:708053224224:web:d9ab9ae6f7fff504b0a545',
    messagingSenderId: '708053224224',
    projectId: 'pabdatabase',
    authDomain: 'pabdatabase.firebaseapp.com',
    databaseURL: 'https://pabdatabase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pabdatabase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYOOm7mImoHpM_Jd-STHPY8wvQ_nBmg5Q',
    appId: '1:708053224224:android:a633d3bbe043ad7cb0a545',
    messagingSenderId: '708053224224',
    projectId: 'pabdatabase',
    databaseURL: 'https://pabdatabase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pabdatabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUJ-vsgB5IhdpZGq1va_1apfQLHj1WEYM',
    appId: '1:708053224224:ios:e6fdcc43873b78abb0a545',
    messagingSenderId: '708053224224',
    projectId: 'pabdatabase',
    databaseURL: 'https://pabdatabase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pabdatabase.firebasestorage.app',
    iosBundleId: 'com.ntr.neuralboost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUJ-vsgB5IhdpZGq1va_1apfQLHj1WEYM',
    appId: '1:708053224224:ios:e6fdcc43873b78abb0a545',
    messagingSenderId: '708053224224',
    projectId: 'pabdatabase',
    databaseURL: 'https://pabdatabase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pabdatabase.firebasestorage.app',
    iosBundleId: 'com.ntr.neuralboost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS0yatbK58dhN-VRLMp9BbVEePCVTkiB4',
    appId: '1:708053224224:web:9ed455685118e0dab0a545',
    messagingSenderId: '708053224224',
    projectId: 'pabdatabase',
    authDomain: 'pabdatabase.firebaseapp.com',
    databaseURL: 'https://pabdatabase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pabdatabase.firebasestorage.app',
  );

}